name: Automake Build

on:
  push:
    branches:
      - branchAutomake
  pull_request:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake autoconf build-essential pkg-config

    - name: Generate configure script
      run: |
        chmod +x autogen.sh  # Ensure the script is executable
        ./autogen.sh  # Run autogen.sh to generate configuration files

    - name: Build tarball
      run: |
        ./configure && make dist
