name: create tarball distribution

on:
  push:
    branches: ["branchAutomake"]
  pull_request:
    branches: ["branchAutomake"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake make g++

      - name: Generate config scripts
        run: |
          aclocal
          autoconf
          automake --add-missing

      - name: Build and configure
        run: |
          ./configure
          make
          make check

      - name: Create tarball distribution
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: program-tarball
          path: program-*.tar.gz

        
